### ISSUE TITLE
Todo - more tests / code clean up

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Zaid-Ajaj/Fable.Remoting#25]
- [x] Saturn integration tests 
- [ ] Test projects using the Nuget package
- [ ] Unit tests 
  - [x] Partially applied proxy functions
  - [ ] Partially applied proxy functions using complex types
  - [ ] Edge-cases for primitive types (NaN, infinity, etc)
