### ISSUE TITLE
Roadmap and next steps

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Zaid-Ajaj/Fable.Remoting#54]
After the [recent discussion](https://github.com/Zaid-Ajaj/Fable.Remoting/issues/50) and a review on the overall architecture of the library, I have decided to make a small rewrite and here are my thoughts on what next steps will be taken and the reason behind them 

 - [ ] Removing the CE based Api
It was a nice addition to the previous api, which was just a function that takes in many parameters.  It makes the internal structure more complicated than it should be and it is just syntactic addition. It will be replaced with good old method chaining: 
```fs
type IMusicStore = { bestAlbums : Async<Album list> }
 
let musicStore = { bestAlbums = Db.getBestAlbums() } 

let musicStoreApi : WebPart = 
   Remoting.createApi()
   |> Remoting.withRouteBuilder (sprintf "/api/%s/%s")
   |> Remoting.fromValue musicStore 
   |> Remoting.buildWebPart
```
- [ ] Removing the [Response Override](https://github.com/Zaid-Ajaj/Fable.Remoting/blob/master/Fable.Remoting.Server/ServerSide.fs#L92) type
Along with custom handlers, they don't really fit in the core idea of the library of abstracting http away, if it is needed, then just use raw http instead
- [ ] Mapping record fields of type `Async<'t>` or `unit -> Async<'t>` to `GET` instead of `POST` request because they don't require input <-> no request body needed so it becomes natural this way
- [ ] Rename `Fable.Remoting.Middleware` to `Fable.Remoting.AspNetCore` and publish to make the library run eveywhere (Giraffe, Saturn, Freya, Nancy etc.) 
- [ ] Integrate with the dependency injection system of Aspnet core with simple way to resolve dependencies with a simple `reader` monad
```fs
let musicStore = reader {
    let! musicDb = resolve<IMusicDb>()
    let! securityOps = resolve<ISecurityOps>() 
    let! context = resolve<HttpContext>() 
    return { bestAlbums = async { return musicDb.getAwesomeAlbums() } }
}

let musicStoreApi = 
    Remoting.createApi()
    |> Remoting.withRouteBuilder (sprintf "/api/%s/%s")
    |> Remoting.fromReader musicStore 
    |> Remoting.build

// later at IApplicationBuidler
app.UseRemoting(musicStoreApi)
```
where `fromReader` is just a syntactic sugar around `HttpContext -> 't` 
- [ ] Add optional dependency injection mechanism to Suave 
Suave doesn't have it's own DI mechanism but we could add it to Suave as an *optional* feature with packages `Fable.Remoting.AutoFac`, `Fable.Remoting.Ninject` to allow use of these ioc containers for Suave like this:
```fs
let configureDependencies() : IContainer =
  let builder = ContainerBuilder() 
  builder.Register<SqlConfig>().As<ISqlConfig>()
  builder.Register<SqlMusicDb>().As<IMusicDb>()
  builder.Build() 

let createMusicStore (db: IMusicDb) = { popularAlbums = db.getPopularAlbums() }

let musicStore = reader {
    let! musicDb = resolve<IMusicDb>()
    let! context = resolve<HttpContext>() // if needed for Suave
    // musicDb.GetType().Name => SqlMusicDb
    createMusicStore  musicDb
}

let musicStoreApi  = 
  Remoting.createApi() 
  |> Remoting.withRouteBuilder (sprintf "/api/%s/%s")
  |> Remoting.withAutoFac (configureDependencies()) // open Fable.Remoting.AutoFac
  |> Remoting.fromReader musicStore 
  |> Remoting.buildWebPart
``` 
- [ ] Remove the contextual handler in favor of the `reader` api   
- [ ] Migrate the `Client` to Fable 2 when Fable 2 becomes stable, the Json converter is already implemented in `Fable.SimpleJson` and hopefully doesn't require any changes in `Fable.Remoting.Json` because it understands JSON representation of Fable 1 as well 

These were my thoughts, I will be able to start working on the rewrite later this week

**Comment by Nhowka** [comment]
I don't understand the `reader` and how it makes it build the endpoints only once

**Comment by irium** [comment]
There is a mistake here:

```
let createMusicStore (db: IMusicDb) = { popularAlbums = db.getPopularAlbums() }

let musicStore = reader {
    let! musicDb = resolve<IMusicDb>()
    let! context = resolve<HttpContext>() // if needed for Suave
    // musicDb.GetType().Name => SqlMusicDb
    createMusicStore  musicDb
}
```

it should be written as this:

```
let getPopularAlbums = reader {
    let! musicDb = resolve<IMusicDb>()
    return musicDb.getPopularAlbumns()
}

let findAlbum name = reader {
    let! musicDb = resolve<IMusicDb>()
    return musicDb.findAlbum name
}

let musicStore = {
    popularAlbums = getPopularAlbums
    findAlbum = findAlbum
}
...
```

**Comment by Zaid-Ajaj** [comment]
The reason the endpoints will be created once is because the builder will be invoked once and will cache the routes, i.e. this block will run once (at least I will make sure that internally, the code that builds routes is run once): 
```fs
let musicStoreApi = 
    Remoting.createApi()
    |> Remoting.withRouteBuilder (sprintf "/api/%s/%s")
    |> Remoting.fromReader musicStore 
    |> Remoting.build
```
it has nothing to do with the `reader`, the `reader` is just a function `'a -> 'b` that in our case will be `HttpContext -> 'b` that seems to allow for functions with *delayed implicit input* : it can chain other `reader`s that require some input (the `'a` parameter, the `HttpContext` in our case) without that input being explicitly defined (that's why the `reader` doesn't have parameters) and when you run it (we will do that internally), the input goes through all chained functions and returns the result (Sorry if this is a bad description, I am also trying to wrap my head around it) 
 
~~Stolen from~~ Inspired by https://fsharpforfunandprofit.com/posts/elevated-world-6/
```fs
type Reader<'a, 'b> = Reader of ('a -> 'b) 

module Reader = 
  let run a (Reader fromAtoB) = 
    let b = fromAtoB a 
    b

  let returnM b = Reader (fun _ -> b) 
  
  let bindM f reader = 
      let nextReader environment =
          let x = run environment reader 
          run environment (f x)
      Reader nextReader

type ReaderBuilder() = 
  member this.Return(x) = Reader.returnM x 
  member this.Bind(x, f) = Reader.bindM f x 

// this is the builder
let reader = ReaderBuilder()
```
the `resolve` functions are also such *delayed input* functions that take in an `HttpContext` and will return a result value:
```fs
let private getService<'t> (context : HttpContext) : 't = 
  if typeof<'t>.GUID = typeof<HttpContext>.GUID
  then context |> unbox<'t>
  else context.RequestServices.GetService(typeof<'t>) :?> 't

let resolve<'t>() = Reader (fun (httpContext: HttpContext) -> getService<'t>(httpContext)) 
   
// a function of `HttpContext -> IMusicStore` with implicit input 
// also an over-used example by now ;p  
let musicStore = reader {
   let! db = resolve<IMusicDb>()
   return someMusicStore db 
}     

// it can be rewritten as an explicit function of HttpContext without a monad/builder etc. 
let musicStore (context: httpContext) = 
    let db = getService<IMusicDb>()
    return someMusicStore db 
```
I hope this clarifies things

**Comment by Zaid-Ajaj** [comment]
@irium It is not a mistake, this is how I am thinking of building this, because otherwise the client would have to invoke the function `findAlbums` like this: `server.findAlbums "some name" ()` which is weird , it also clutters the definition of the protocol: 
```fs
type IMusicStore<'t> = { findAlbums : string -> 't -> Async<Album list>
```
using the `reader` at the protocol level is a lot cleaner and simpler (especially from the client pov), even if some functions don't require some of the services you `resolve`, the overhead is negligable, if you have some really expensive-to-create dependency then just write `let context = resolve<HttpContext>()` at the protocol level and from inside the function in subject, you can resolve `let expensiveService = getService<IService>(context)`

**Comment by Zaid-Ajaj** [comment]
> Does it have to create the implementation at every request? I'm not liking that..

Creating the implementation on every request is extremely cheap / negligible. it is just creating a record. This is only *if* you wanted to access and context and dependencies, otherwise you could just create the implementation yourself and write `Remoting.fromValue impl`. This is no different than any mvc/web-api controller that gets instantiated every request based on its dependencies 

> I believe the server and client are developed by the same person, so using unit on the client and the interface to be injected on the server could make it easier on both sides. 

Using `IProtocol<unit>` on the client works, that is right, but it always seemed like a hack, especially when you actually need to send `()` for injected paramters, it makes the protocol definition really weird, the protocol definition shouldn't care about what is and what is not injected in the implementation.

**Comment by irium** [comment]
@Zaid-Ajaj Yeah, I've already know what the `Reader` is and what problems it solves. At the end it's me, who proposed to use it :)

But again, using "overused example":

```
let musicStore = reader {
   let! db = resolve<IMusicDb>()
   return someMusicStore db 
}     
```

I see `musicStore` as `web part` with multiple methods - routes. Try to rewrite the example to show how it will be looking when using two or more methods from `IMusicDb` and how it will be routing to? I don't see how it could be done now, passing a single, top `reader`.

**Comment by irium** [comment]
@Nhowka Creating implementation is not an issue here, at all. It's abstracted away completely. You could create it beforehand and just always return already cached instance.

This is matter of DI system in use - everyone DI library (like Autofac, Ninject etc) allows you to configure dependency as `instance` by passing already created instance to them. Or, as `singleton` - it will be created only once at first request. As @Zaid-Ajaj already said in almost cases creating dependency is very cheap.

**Comment by Zaid-Ajaj** [comment]
@irium I was trying to explain it to @Nhowka but you posted while I was writing :) 

>  I don't see how it could be done now, passing a single, top reader.

Do you mean from a users perspective or internally (how the library will decide what function to invoke?) 

here is the full example (that I haven't tested yet):
```fs
type IMusicDb = 
    abstract getRecentAlbums : unit -> Async<Album list>
    abstract searchAlbumsByTitle : string -> Async<Album list>

// the protocol
type IMusicStore = {
    recentAlbums : Async<Album list>
    searchByTitle : string -> Async<Album list>
}

// Assuming you registered some implementation of IMusicDb in your container

// the implementation : Reader<HttpContext, IMusicStore>
let musicStore = reader {
   let! musicDb = resolve<IMusicDb>()
   return {
      recentAlbums = musicDb.getRecentAlbums()
      
      searchByTitle = fun title -> async {
           let! searchResults = musicDb.searchAlbumsByTitle title 
           return searchResults 
      }
   }
}

let musicStoreApi =
  Remoting.createApi()
  |> Remoting.withRouteBuilder (sprintf "/api/%s/%s")
  |> Remoting.fromReader  musicStore 
  |> Remoting.build

// from the client 
async  { 
  let musicStore = createMusicStoreProxy()
  return! musicStore.searchByTitle "Metallica" 
}
```
or you can create a seperate factory function:
```fs
let createMusicStore (db: IMusicDb) = {
   recentAlbums = musicDb.getRecentAlbums()
      
   searchByTitle = fun title -> async {
       let! searchResults = musicDb.searchAlbumsByTitle title 
       return searchResults 
   }  
}

let musicStore = reader {
  let! musicDb = resolve<IMusicDb>()
  return createMusicStore musicDb 
}
```
Is this what you meant?

**Comment by Zaid-Ajaj** [comment]
heck, why not even let the dependency injection framework create the `IMusicStore` for you as `singleton` so that you will be able to just `resolve` it right away from the container like this
```fs
let musicStore = reader { return! resolve<IMusicStore>() } 
```
Not sure how you would register it though with the container

**Comment by Nhowka** [comment]
> Mapping record fields of type Async<'t> or unit -> Async<'t> to GET instead of POST

Thinking about it, those functions are less useful if they are referentially transparent and less likely to always return the same result... Should we add a `Cache-Control: no-cache` header to be safe?

**Comment by Zaid-Ajaj** [comment]
>Should we add a Cache-Control: no-cache header to be safe?

That's a good point, we won't cache anything, users can cache their data if they need to 

also, I think `reader` is too general, what do you think about calling it `implicitContext` or just `context`?

**Comment by Zaid-Ajaj** [comment]
Theoretically it will be something as follows, I still need to test things out (please wait before you start implementing anything because our work will then overlap) 

```fs
// namespace Fable.Remoting.Server <- the shared options 

type IoCContainer = 
  abstract Resolve<'t> : unit -> 't 

type RemotingOptions = { (* ... *); Container : Option<IoCContainer> } 

/// DI Container plugin
/// namespace Fable.Remoting.AutoFac 
/// open AutoFac

module Remoting = 
  let withAutoFac (container: IContainer) (options: RemotingOptions) = 
    let autoFacContainer = { new IoCContainer with self.Resolve<'t>() = container.Resolve<'t>() } 
    { options with  Container = Some autoFacContainer } 
   
```
